import Image from 'next/image';

import DynamicHeading from '@/components/layout/userManagement/onboard/DynamicHeading';
import Steps from '@/components/layout/userManagement/onboard/Steps';
import UserForm from '@/components/layout/userManagement/UserForm';

export const metadata = {
  title: 'Eminence | On Board',
  description: 'Generated by create next app',
};

export default function StepsLayout({ children }) {
  return (
    <section className="bg-primary-black py-10 min-h-screen overflow-hidden">
      <Steps />

      <div className="flex flex-col items-center mt-10 relative">
        <Image
          src="/images/userManagement/form-bg-circles.svg"
          width={742}
          height={742}
          alt=""
          className="absolute top-0 left-[50%] transform -translate-x-1/2"
        />
        <DynamicHeading />
        <UserForm>{children}</UserForm>
      </div>
    </section>
  );
}
