import Image from 'next/image';

export const metadata = {
  title: 'Eminence | User',
  description: 'Generated by create next app',
};

export default function RoutesLayout({ children }) {
  return (
    <section className="bg-primary-black">
      <div className="flex flex-col items-center relative">
        <Image
          src="/images/userManagement/form-bg-circles.svg"
          width={742}
          height={742}
          alt=""
          className="absolute top-0 left-[50%] transform -translate-x-1/2"
        />

        {children}
      </div>
    </section>
  );
}
